# Generated by Django 6.0 on 2025-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
